### ISSUE TITLE
LockStep compilation issue

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/PX4-FlightGear-Bridge#1]
FG build of PX4 need to be built without LockStep, but I am not able to set up CMake scripts to build PX4 binary for FG without Lockstep and Gazebo Px4 Binary with LockStep. 

(https://github.com/PX4/Firmware/pull/14539/files#diff-a0bb2f464f832f23df5a4d5b1737cef2) -- I think this damage tests

**Comment by slimonslimon** [comment]
Solved in PR of PX4
