### ISSUE TITLE
Primary EKF changed X (unhealthy) -> X

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/PX4-FlightGear-Bridge#27]
A suspicious warning message emerged in the terminal after running the simulation. 

![image](https://user-images.githubusercontent.com/1194177/103778729-f55c8400-5032-11eb-9742-b709a547dabb.png)

The effect on simulator performance is unknown to me. It seems to works correctly.

**Comment by roman-dvorak** [comment]
It is possible that this is causing this problem - bad estimation of altitude. 
![obrazek](https://user-images.githubusercontent.com/5196729/104629512-e2ccf500-5699-11eb-8f39-aa427db4d052.png)

Baro and GPS data from FG looks fine. But estimation is bad. Interesting is, that jitter offset is always same (200 m). 


In PX4 console I can see the same warnings as @kaklik

**Comment by roman-dvorak** [comment]
The problem from the last comment looks solved by disabling multiple EKF (https://github.com/PX4/PX4-Autopilot/pull/14650). 

New parameter configuration is here:
![obrazek](https://user-images.githubusercontent.com/5196729/104739008-8378ee80-5746-11eb-8ef1-aa6b4a4e49e7.png)

So far, I am not able to repeat it with another model.
It seems not to be related to PX4-FlightGear-bridge. 

@kaklik, can you try to reproduce this bug with the use of the following parameters?

    ekf2_multi_imu : 3
    sens_imu_mode`: 0

@dagar Please, Is possible that one of the multiple (Multi-EKF) estimators estimate a different altitude. And constant switching sometimes comes across a "problematic" estimator?

**Comment by dagar** [comment]
Can you share the full log? https://logs.px4.io/

**Comment by roman-dvorak** [comment]
Yes, log file is here: 
https://logs.px4.io/plot_app?log=b3c6ce24-aad7-4040-8c7e-cbcbf98b1fb1

**Comment by dagar** [comment]
2 issues (so far)

1. I believe the rapid switching should be resolved with https://github.com/PX4/PX4-Autopilot/pull/16518. The logging for this is also a lot better in current master (https://github.com/PX4/PX4-Autopilot/pull/16529). In 
<img width="1353" alt="Screen Shot 2021-01-15 at 7 49 56 PM" src="https://user-images.githubusercontent.com/84712/104792015-e11f3200-576a-11eb-8e83-9888e96e3137.png">

2. the difference in altitude estimates per estimator
      - only 1 out of 4 logged ekf2 instances have a different altitude estimate
<img width="1347" alt="Screen Shot 2021-01-15 at 7 54 43 PM" src="https://user-images.githubusercontent.com/84712/104792176-8803ce00-576b-11eb-8135-831153679c1f.png">


I believe the offset in z estimates can be explained by the baro altitude ramping combined with slightly different timing of height resets.

<img width="1789" alt="Screen Shot 2021-01-15 at 8 11 51 PM" src="https://user-images.githubusercontent.com/84712/104792863-f5b0f980-576d-11eb-9c05-233fc6a028a6.png">

Note, this isn't actually a problem as long as all consumers of estimator data respect the resets, although I'd still like to minimize these differences as much as possible. https://github.com/PX4/PX4-Autopilot/blob/1c0ed74d6a91d39cffbddf8ff5e6a8e1c329ebb1/msg/vehicle_local_position.msg#L20-L21

**EDIT:** I think it's the case `baro hgt timeout - reset to baro` that causes the offset, this might technically be a bug.

**Comment by slimonslimon** [comment]
`baro hgt timeout - reset to baro` - what frequency of messages is expected from baro? (or where can i found it in code?)
(or I missunderstand the `baro hgt timeout` message?)

FG sends its messages into bridge maximaly at FPS rate, this bridge can do some upsampling by resending same message with random noise - (normal distribution, but t dont know what variance shoud be set - i set it somehow....)

**Comment by dagar** [comment]
> `baro hgt timeout - reset to baro` - what frequency of messages is expected from baro? (or where can i found it in code?)
> (or I missunderstand the `baro hgt timeout` message?)
> 
> FG sends its messages into bridge maximaly at FPS rate, this bridge can do some upsampling by resending same message with random noise - (normal distribution, but t dont know what variance shoud be set - i set it somehow....)

Low rate (eg 10 Hz) is fine as long as the jitter isn't horrible. The message is perhaps a bit misleading because it's not necessarily a timeout (gap in data), it's more of a general problem with that height source (like high baro innovations).

**Comment by dagar** [comment]
This bug in the ekf2selector also may have been a factor. https://github.com/PX4/PX4-Autopilot/pull/16622
Even though you had estimators that ended up with height offsets, switching between them should still have been handled smoothly by the controllers.

**Comment by slimonslimon** [comment]
@dagar thank you for your comments! 

It seems that barometric pressure ramping is caused by FG initialization (FG probably models The Big bang...) I will put a 5sec delay, before start sending messages into PX4.

But "Primary EKF changed X (unhealthy) -> X" is still unresolved. Maybe an increase in sending messages to PX4 produces fewer messages but, I'm not sure.

**Comment by kaklik** [comment]
> 
> @kaklik, can you try to reproduce this bug with the use of the following parameters?
> 
> ```
> ekf2_multi_imu : 3
> sens_imu_mode`: 0
> ```

Yes, the issue happens in the case where the multiple IMUs are activated with SITL simulation.  Disabling multiple IMUs by setting:

     ekf2_multi_imu : 1
     sens_imu_mode: 1
 
solves the problem.  But in the case of updated PX4Firmware/master, a new similar problem emerges:

    ERROR [ekf2] 0 - vehicle_magnetometer lost, generation 22378 -> 22381
    ERROR [ekf2] 0 - vehicle_magnetometer lost, generation 22383 -> 22386
    ERROR [ekf2] 0 - vehicle_magnetometer lost, generation 22386 -> 22388
    ERROR [ekf2] 0 - vehicle_magnetometer lost, generation 22389 -> 22393
    ERROR [ekf2] 0 - vehicle_magnetometer lost, generation 22395 -> 22398
    ERROR [ekf2] 0 - vehicle_magnetometer lost, generation 22400 -> 22402
    ERROR [ekf2] 0 - vehicle_magnetometer lost, generation 22404 -> 22406
    ERROR [ekf2] 0 - vehicle_magnetometer lost, generation 22408 -> 22410
    ERROR [ekf2] 0 - vehicle_magnetometer lost, generation 22410 -> 22412

The PX4 generate thousands of such messages.  The message is [generated here](https://github.com/PX4/PX4-Autopilot/blob/master/src/modules/ekf2/EKF2.cpp#L1425). But I do not understand the meaning of this message.

**Comment by dagar** [comment]
> The PX4 generate thousands of such messages. The message is generated here. But I do not understand the meaning of this message.

It means `ekf2` isn't keeping up with `vehicle_magnetometer` publications for some reason. This is a new debugging message only recently added to master to find potential problems and it needs to be investigated.

**Comment by dagar** [comment]
> > The PX4 generate thousands of such messages. The message is generated here. But I do not understand the meaning of this message.
> 
> It means `ekf2` is isn't keeping up with `vehicle_magnetometer` publications for some reason. This is a new debugging message only recently added to master to find potential problems and it needs to be investigated.

Should be fixed by https://github.com/PX4/PX4-Autopilot/pull/16698.

**Comment by slimonslimon** [comment]
Thank you @dagar ! It seems to work!

**Comment by kaklik** [comment]
The FlightGear-PX4 working setup has been reached again. Required parameters setup: 

     ekf2_multi_imu : 1
     sens_imu_mode: 1
 
Altitude ramp up solved by delay at beginning of the simulation. It is tested with current PX4upstream/master firmware. 

Thanks to all! :)

**Comment by BrenoPimentel** [comment]
I got the same error trying to write PX4 commands on prompt, however, i just restart my PC and launch the software again and well done. It works normally :)

**Comment by lygoon** [comment]
I also encountered this error（WARN  [ekf2] primary EKF changed 0 (unhealthy) -> 2）, but I don't know where to correct it. Which file can I modify? thank you!

**Comment by kaklik** [comment]
> I also encountered this error（WARN [ekf2] primary EKF changed 0 (unhealthy) -> 2）, but I don't know where to correct it. Which file can I modify? thank you!

Please check, that you are running the up-to-date FlightGear-Bridge code.  You could also disable this message by disabling ekf2_multi_imu in PX4 parameters.
