### ISSUE TITLE
Multi-vehicle simulation support

### ISSUE THREAD

**Issue by slimonslimon** [ThunderFly-aerospace/PX4-FlightGear-Bridge#4]
There are exist these three connections, which needs to be initialized correctly: 

- FG<->FGServer
- Bridge<->FG
- Bridge<->PX4

For multi-vehicle simulation we need to solve the following problems:
 
- [x] multiple FG instances should be ready to connect to the same FG server, but every FG instance needs to pick a unique port for incoming communication (by FG start-up parameters). The communication parameters need to be defined from the PX4 bridge side. 
- [x] FG-bridge and FG need to configure parameters ( e.g. FG startup parameters, and FG-bridge internal properties).
- [x] FG-bridge to PX4 also need set up a port for Communication - (vehicle can setup listening port in its boot e.g. bridge side)
- [x] Find a way how to find "empty" px4 proces number

**Comment by Jaeyoung-Lim** [comment]
Multivehicle support would be awesome!

@slimonslimon For the port configuration, [this](https://github.com/PX4/Firmware/blob/master/Tools/gazebo_sitl_multiple_run.sh) script might be useful to compare how it is done for gazebo

**Comment by slimonslimon** [comment]
Thank you for your comment!
Our solution for FG will work in a little bit another way because we need to spawn multiple types of vehicles.

I'm close to working example now. 

@Jaeyoung-Lim  Do you have some experiences with communication and orchestration of multiple vehicles? And are you able to run current Px4<->FG SITL?

**Comment by slimonslimon** [comment]
Now, there is an experimental branch flightgear-multi, which supports: 
`make px4_sitl_nolockstep flightgear_plane___multi`
And you are able to run it multiple times. You only need to connect FG to the server manually, for now. (It will be automated later.)

There is one other problem with selecting "empty" "px4id" - now it counts running px4 instances - this can work only on the first run. (You cannot restart any instance separately)

**Comment by Jaeyoung-Lim** [comment]
@slimonslimon IMHOI I would prefer moving the multivehicle sim to a separate script, rather than making it part of the make target (e.g. the script link I linked above) so that we can be more versatile on the number of vehicles.

For example, for gazebo you can specify arbitrary number of vehicles and targets through the script

**Comment by slimonslimon** [comment]
Thank you for your comment! I will improve this later.

**Comment by slimonslimon** [comment]
The last problem of selecting PX4 ID was passed to user start script - it should be set by environmental variable in the experimental branch 

but this problem is not part of the FG bridge, It is the problem of start scripts. 

The bridge has multi-vehicle support.
